### ISSUE TITLE
Cannot produce model.bin after training

### ISSUE THREAD

**Issue by chontipan** [neulab/incremental_tree_edit#1]
After I run "bash scripts/githubedits/train.sh source_data/githubedits/configs/graph2iteredit.seq_edit_encoder.20p.json"

and the err.log says

![image](https://user-images.githubusercontent.com/9138402/114315986-1baf2580-9b34-11eb-8387-f627b1cf6ca6.png)

Could you please guide me how to fix this err?

**Comment by LittleYUYU** [comment]
Hi @chontipan, it seems you are running the imitation learning experiment with a wrong config file, or you have set up the train.sh script incorrectly. 

If you only want to train the model with supervised learning, please uncomment **only line 21-25** in train.sh and run:
```
bash scripts/githubedits/train.sh source_data/githubedits/configs/graph2iteredit.seq_edit_encoder.20p.json
```

If you want to further train the model with imitation learning, please uncomment **only line 27-31** in train.sh and then configure and run the experiment as described [here](https://github.com/neulab/incremental_tree_edit#training).

Please let us know if this looks clear. We will revise the README with clarification as well.

**Comment by chontipan** [comment]
Hi, I got another error when I uncomment only line 21-25 in train.sh

![image](https://user-images.githubusercontent.com/9138402/114323361-64c4a100-9b57-11eb-928a-e0ba85a94859.png)

**Comment by chontipan** [comment]
Hi, thank for the reply. I got another issue when I uncomment only line 21-25 in train.sh and run.
![114323361-64c4a100-9b57-11eb-928a-e0ba85a94859](https://user-images.githubusercontent.com/9138402/114323657-c33e4f00-9b58-11eb-98b1-89308530ff71.png)

**Comment by LittleYUYU** [comment]
Hi @chontipan, please prepare the data following [here](https://github.com/neulab/incremental_tree_edit#2-data).

**Comment by chontipan** [comment]
Hi, I do 

cd source_data
tar -xzvf githubedits.tar.gz

and do not get githubedits.dev.jsonl.

![image](https://user-images.githubusercontent.com/9138402/114324533-3053e380-9b5d-11eb-8fb1-b6bc7be04606.png)

**Comment by LittleYUYU** [comment]
Hi @chontipan, please make sure you have pulled down the latest version of code and data from this repository. We have made updates since the initial commit. 

The missing data should have been included in the latest zipped file. You can also download it from [Yin et al., (2019)](http://www.cs.cmu.edu/~pengchey/githubedits.zip), but please make sure that the data files are consistently organized as we described in [Sec 2. Data](https://github.com/neulab/incremental_tree_edit#2-data).

**Comment by chontipan** [comment]
Thank you. It is running now.
