### ISSUE TITLE
Where can we get the Syntax.xml file for other languages?

### ISSUE THREAD

**Issue by v587su** [neulab/incremental_tree_edit#3]
Hi, 
Your work is great. I want to reproduce your model on Java datasets. But the `Syntax.xml` and `grammar.json` file in `asdl/lang/csharp` is for Csharp. Are there any public resources for Java?
Thank you.

**Comment by LittleYUYU** [comment]
Hi @v587su, thank you! We don't have Java ASDL implementation at this moment, but we provide some guidelines (https://github.com/neulab/incremental_tree_edit#41-applications-to-other-languages) for adapting the model to other languages. We also encourage you to check out the [TranX](https://github.com/pcyin/tranX/tree/master/asdl/lang) code and see if it covers any languages of your interest. Feel free to let us know if you encounter any issues while using our code!

**Comment by v587su** [comment]
> Hi @v587su, thank you! We don't have Java ASDL implementation at this moment, but we provide some guidelines (https://github.com/neulab/incremental_tree_edit#41-applications-to-other-languages) for adapting the model to other languages. We also encourage you to check out the [TranX](https://github.com/pcyin/tranX/tree/master/asdl/lang) code and see if it covers any languages of your interest. Feel free to let us know if you encounter any issues while using our code!

Thanks. Maybe this file is available for Java. https://github.com/tree-sitter/tree-sitter-java/blob/master/src/node-types.json#L2
