### ISSUE TITLE
What is the CSharpHypothesis for?

### ISSUE THREAD

**Issue by v587su** [neulab/incremental_tree_edit#4]
Hi. I am trying to transfer your model to my Java dataset. It is not a easy work because of the difference between the grammar of C# and Java. I have already produced the ASDLTree with `Field` class modified.  

Now I have difficulty in understanding the `CSharpHypothesis` class. 

-What is its function? 
-Why does the `SubstitutionSystem` use `Hypothesis` intead of `CSharpHypothesis`?

It will be a great help if you could answer these questions.

**Comment by LittleYUYU** [comment]
Hi, 

`CSharpHypothesis` is a subclass of `asdl.hypothesis.Hypothesis`; it's used by Graph2Tree's transition system (https://github.com/neulab/incremental_tree_edit/blob/master/asdl/lang/csharp/csharp_transition.py#L136).

`SubstitutionSystem` is using the class of `tree.hypothesis.Hypothesis`, which is designed for Graph2Edits.

Wish that answers your question!
